### ISSUE TITLE
Whiteboard Crashes after using it for 25+ minutes

### ISSUE THREAD

**Issue by byquanton** [nextcloud/whiteboard#258]
I used a whiteboard for about 25 Minutes and the server suddenly crashed. I had it open on 3 devices with the same Nextcloud account.
All changes were lost and nothing was saved to the Nextcloud (reopening it resulted in an empty file).

It was not possible to use the built-in download button to back up after the server crashed because closing the error alert stopped the whole "exalidraw" session and while the message was displayed it was not possible to interact with the page.

Logs:
```
[12808] Room data synced. Users: 1, Last edited by: *censored*, files: 4
[socket:*censored*] Disposing room
file:///app/websocket_server/SocketManager.js:160
			user: data.user,
			           ^

TypeError: Cannot read properties of undefined (reading 'user')
at file:///app/websocket_server/SocketManager.js:160:16
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
at async Promise.all (index 0)
at async SocketManager.serverBroadcastHandler (file:///app/websocket_server/SocketManager.js:207:29)
````

**Comment by Grizaster** [comment]
same here!

**Comment by TobiasHofmaenner** [comment]
I have the exact same problem.
i added:
```
restart: unless-stopped
```
to my docker-compose.yaml but it not really a fix...

**Comment by Timbio** [comment]
I have the same issue as well.

**Comment by TobiasHofmaenner** [comment]
I guess we should check and make sure that ```data.user``` is not ```undefined``` in SocketManager.js in the function:
```
	async getUserSocketsAndIds(roomID) {
		const sockets = await this.io.in(roomID).fetchSockets()
		return Promise.all(sockets.map(async (s) => {
			const data = await this.socketDataManager.getSocketData(s.id)
			return {
				socketId: s.id,
				user: data.user,
				userId: data.user.id,
			}
		}))
	}
```

**Comment by hweihwang** [comment]
Thank you for reporting this issue! We've been able to reproduce the crash locally after extended usage.

@TobiasHofmaenner's suggestion about adding empty checks for `data.user` in `SocketManager.js` might help prevent the crashes temporarily.

We'll investigate the cause and provide proper fixes in upcoming releases. Thank you!
